//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetails
    {
        public int BankID { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> CustomerCount { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<int> CreditCardCount { get; set; }
        public Nullable<int> EstablishmentYear { get; set; }
        public Nullable<decimal> CustomerPortfolio { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BankWebsite { get; set; }
    }
}
